spring:
  application:
    name: springai-demo
  ai:
    openai:
      base-url: https://opencode.ai/zen
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: big-pickle
          temperature: 0.8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/home?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

logging:
  level:
    org.springframework.ai: debug
    per.mk.springai.demo: debug

server:
  port: 8090

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
