server:
  port: 9005

spring:
  application:
    name: home-service
  datasource:
    url: jdbc:mysql://localhost:3306/home?useSSL=false&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    platform: mysql
  redis:
    cluster:
      nodes: 10.100.210.165:7001,10.100.210.165:7002,10.100.210.165:7003,10.100.210.166:7001,10.100.210.166:7002,10.100.210.166:7003

logging:
  file: D:/logs/springcloud-demo/home-service.log
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/