server:
  port: 9005

spring:
  application:
    name: home-service
  datasource:
    url: jdbc:mysql://localhost:3306/home?useSSL=false&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    platform: mysql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/