spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/home?useSSL=false&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-home.sql

logging:
  file:
    name: D:/mk-logs/home-service.log
  level:
    root: INFO

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.work.model