server:
  port: 9200

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 路由规则1：本地home-service（直接URL）
        - id: home-service
          uri: http://localhost:9005
          predicates:
            - Path=/home-service/**
          filters:
            - StripPrefix=1  # 移除/local/home-service前缀

# 连接远程Eureka（但不注册自己）
eureka:
  client:
    service-url:
      defaultZone: http://10.50.10.113:9100/eureka/
    register-with-eureka: false  # 关键！不注册本地Gateway