server:
  port: 9200

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: home-service
          uri: http://localhost:9005
          predicates:
            - Path=/home-service/**
          filters:
            - StripPrefix=1
        - id: home-admin
          uri: http://localhost:80
          predicates:
            - Path=/home-admin/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.9:9100/eureka/