server:
  port: 9100

logging:
  file:
    name: D:/mk-logs/eureka-server.log
  level:
    root: INFO

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/