server:
  port: 9002

spring:
  application:
    name: work-admin
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: redis
    redis:
      namespace: mk:login
  redis:
    cluster:
      nodes: 10.100.210.165:7001,10.100.210.165:7002,10.100.210.165:7003,10.100.210.166:7001,10.100.210.166:7002,10.100.210.166:7003

logging:
  file:
    name: D:/mk-logs/work-admin.log
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info  # 暴露健康检查端点
  endpoint:
    health:
      show-details: always    # 显示详细信息