server:
  port: 8086

spring:
  application:
    name: home-admin
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/