server:
  port: 9006

spring:
  application:
    name: home-admin
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

logging:
  file:
    name: D:/mk-logs/home-admin.log
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/

netty:
  websocket:
    network-card-name: wlan0