server:
  port: 9001

spring:
  application:
    name: work-service
  datasource:
    url: jdbc:mysql://localhost:3306/work?useSSL=false&characterEncoding=utf8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    platform: mysql
  redis:
    cluster:
      nodes: 10.100.210.165:7001,10.100.210.165:7002,10.100.210.165:7003,10.100.210.166:7001,10.100.210.166:7002,10.100.210.166:7003

logging:
  file:
    name: D:/mk-logs/work-service.log
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.work.model

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
